In [1]:
import pandas as pd
import numpy as np

C:\Users\ethan\AppData\Local\Temp\ipykernel_15064\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### preprocessing

In [2]:
df = pd.read_csv("beer_reviews.csv")
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.518829e+06,1.586614e+06
mean,3.130099e+03,1.224089e+09,3.815581e+00,3.735636e+00,3.841642e+00,3.743701e+00,3.792860e+00,7.042387e+00,2.171279e+04
std,5.578104e+03,7.654427e+07,7.206219e-01,6.976167e-01,6.160928e-01,6.822184e-01,7.319696e-01,2.322526e+00,2.181834e+04
min,1.000000e+00,8.406720e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,3.000000e+00
25%,1.430000e+02,1.173224e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.717000e+03
50%,4.290000e+02,1.239203e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.390600e+04
75%,2.372000e+03,1.288568e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.944100e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731700e+04

In [3]:
df.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883
5,1075,Caldera Brewing Company,1325524659,3.0,3.5,3.5,oline73,Herbed / Spiced Beer,3.0,3.5,Caldera Ginger Beer,4.7,52159
6,1075,Caldera Brewing Company,1318991115,3.5,3.5,3.5,Reidrover,Herbed / Spiced Beer,4.0,4.0,Caldera Ginger Beer,4.7,52159
7,1075,Caldera Brewing Company,1306276018,3.0,2.5,3.5,alpinebryant,Herbed / Spiced Beer,2.0,3.5,Caldera Ginger Beer,4.7,52159
8,1075,Caldera Brewing Company,1290454503,4.0,3.0,3.5,LordAdmNelson,Herbed / Spiced Beer,3.5,4.0,Caldera Ginger Beer,4.7,52159
9,1075,Caldera Brewing Company,1285632924,4.5,3.5,5.0,augustgarage,Herbed / Spiced Beer,4.0,4.0,Caldera Ginger Beer,4.7,52159

In [4]:
df.dropna(inplace=True)
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06,1.518478e+06
mean,3.074306e+03,1.225332e+09,3.823938e+00,3.746218e+00,3.850383e+00,3.753735e+00,3.804082e+00,7.042488e+00,2.140575e+04
std,5.544339e+03,7.583455e+07,7.172663e-01,6.953440e-01,6.143106e-01,6.793350e-01,7.286079e-01,2.322568e+00,2.178033e+04
min,1.000000e+00,8.406720e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,5.000000e+00
25%,1.410000e+02,1.175562e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.654000e+03
50%,4.170000e+02,1.240356e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.283000e+04
75%,2.298000e+03,1.289086e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.923600e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731600e+04

In [5]:
df.drop_duplicates(df.columns.delete(2), keep="first", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1517728 entries, 0 to 1586613
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   brewery_id          1517728 non-null  int64
 1   brewery_name        1517728 non-null  object
 2   review_time         1517728 non-null  int64
 3   review_overall      1517728 non-null  float64
 4   review_aroma        1517728 non-null  float64
 5   review_appearance   1517728 non-null  float64
 6   review_profilename  1517728 non-null  object
 7   beer_style          1517728 non-null  object
 8   review_palate       1517728 non-null  float64
 9   review_taste        1517728 non-null  float64
 10  beer_name           1517728 non-null  object
 11  beer_abv            1517728 non-null  float64
 12  beer_beerid         1517728 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 162.1+ MB

Only keep the latest review of a specific beer by reviewer

In [6]:
df = df.sort_values(by=['review_time']).drop_duplicates(["beer_beerid", "review_profilename"], keep="last")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1504037 entries, 286273 to 551371
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   brewery_id          1504037 non-null  int64
 1   brewery_name        1504037 non-null  object
 2   review_time         1504037 non-null  int64
 3   review_overall      1504037 non-null  float64
 4   review_aroma        1504037 non-null  float64
 5   review_appearance   1504037 non-null  float64
 6   review_profilename  1504037 non-null  object
 7   beer_style          1504037 non-null  object
 8   review_palate       1504037 non-null  float64
 9   review_taste        1504037 non-null  float64
 10  beer_name           1504037 non-null  object
 11  beer_abv            1504037 non-null  float64
 12  beer_beerid         1504037 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 160.6+ MB

pruning outliers

In [7]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06,1.504037e+06
mean,3.076464e+03,1.225622e+09,3.822327e+00,3.745169e+00,3.849578e+00,3.752468e+00,3.802485e+00,7.043460e+00,2.145173e+04
std,5.545422e+03,7.572728e+07,7.173626e-01,6.950982e-01,6.141191e-01,6.792041e-01,7.285974e-01,2.323306e+00,2.179520e+04
min,1.000000e+00,8.843904e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,5.000000e+00
25%,1.410000e+02,1.175960e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.657000e+03
50%,4.170000e+02,1.240629e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.300900e+04
75%,2.299000e+03,1.289275e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.928600e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731600e+04

In [8]:
print(7.043460 + (3 * 2.323306))

14.013378

In [9]:
df = df.query("review_overall > 0 and review_appearance > 0 and beer_abv < 14.013378")

In [10]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06,1.489428e+06
mean,3.042554e+03,1.225494e+09,3.823240e+00,3.741726e+00,3.847874e+00,3.749954e+00,3.799880e+00,6.944488e+00,2.145299e+04
std,5.530976e+03,7.578802e+07,7.151378e-01,6.941210e-01,6.140172e-01,6.779735e-01,7.270947e-01,2.082946e+00,2.181191e+04
min,1.000000e+00,8.846496e+08,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,5.000000e+00
25%,1.410000e+02,1.175740e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.639000e+03
50%,4.130000e+02,1.240529e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.314200e+04
75%,2.210000e+03,1.289218e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.929600e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,1.400000e+01,7.731600e+04

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1489428 entries, 764128 to 551371
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   brewery_id          1489428 non-null  int64
 1   brewery_name        1489428 non-null  object
 2   review_time         1489428 non-null  int64
 3   review_overall      1489428 non-null  float64
 4   review_aroma        1489428 non-null  float64
 5   review_appearance   1489428 non-null  float64
 6   review_profilename  1489428 non-null  object
 7   beer_style          1489428 non-null  object
 8   review_palate       1489428 non-null  float64
 9   review_taste        1489428 non-null  float64
 10  beer_name           1489428 non-null  object
 11  beer_abv            1489428 non-null  float64
 12  beer_beerid         1489428 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 159.1+ MB

### one hot encoding

In [12]:
def style_encoding(df: pd.DataFrame, col: str) -> pd.DataFrame:
    hot_encoded = pd.get_dummies(df[col], dtype=np.int64, prefix=col)
    df_new = pd.concat([df.drop(col, axis=1), hot_encoded], axis=1)
    return df_new

In [13]:
df_encoded = style_encoding(df, "beer_style")
#df_encoded = style_encoding(df_encoded, "brewery_name")
df_encoded.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,...,beer_style_Scotch Ale / Wee Heavy,beer_style_Scottish Ale,beer_style_Scottish Gruit / Ancient Herbed Ale,beer_style_Smoked Beer,beer_style_Tripel,beer_style_Vienna Lager,beer_style_Weizenbock,beer_style_Wheatwine,beer_style_Winter Warmer,beer_style_Witbier
764128,144,Sprecher Brewing Company,884649601,4.5,4.0,4.0,BeerAdvocate,4.0,4.0,Special Amber,...,0,0,0,0,0,1,0,0,0,0
1417077,139,Shipyard Brewing Co.,885340801,4.0,3.5,3.0,BeerAdvocate,3.5,4.0,Tremont Ale,...,0,0,0,0,0,0,0,0,0,0
78405,140,Sierra Nevada Brewing Co.,886723201,4.5,4.0,4.0,BeerAdvocate,4.0,4.5,Sierra Nevada Bigfoot Barleywine Style Ale,...,0,0,0,0,0,0,0,0,0,0
1526516,45,Brooklyn Brewery,887155201,4.0,2.5,3.0,Todd,3.5,3.5,Brooklyn Lager,...,0,0,0,0,0,0,0,0,0,0
1526153,45,Brooklyn Brewery,887414401,3.0,4.0,3.0,BeerAdvocate,3.0,3.0,Brooklyn East India Pale Ale,...,0,0,0,0,0,0,0,0,0,0
1037995,100,McNeill's Brewery,887414401,4.0,3.5,3.5,Todd,3.5,4.0,McNeill's Firehouse Amber Ale,...,0,0,0,0,0,0,0,0,0,0
1037602,100,McNeill's Brewery,887673601,4.0,3.5,4.0,Todd,3.0,3.5,McNeill's Champ Ale,...,0,0,0,0,0,0,0,0,0,0
921890,155,Upper Canada Brewing Company,887673601,4.5,3.0,3.0,BeerAdvocate,4.0,4.5,Lager,...,0,0,0,0,0,0,0,0,0,0
769741,42,Brewery Ommegang,887760001,4.5,4.0,4.0,Todd,4.0,4.5,Ommegang (Abbey Ale),...,0,0,0,0,0,0,0,0,0,0
1029677,138,Shepherd Neame Ltd,888019201,4.0,4.0,4.0,BeerAdvocate,3.5,4.0,Spitfire (Premium Ale Export),...,0,0,0,0,0,0,0,0,0,0

In [14]:
len(pd.unique(df_encoded["brewery_name"]))

5154

In [15]:
len(pd.unique(df_encoded["brewery_id"]))

5229

^ Why are these different?

dataframe becomes too large if I one hot encode breweries. I will try target encoding (w.r.t. overall_rating) instead

In [16]:
from sklearn.preprocessing import TargetEncoder
def target_encoding(df: pd.DataFrame, col: str, target_col: str, smooth: bool = True) -> pd.DataFrame:
    if smooth:
        targ_enc = TargetEncoder(shuffle=False)
    else:
        targ_enc = TargetEncoder(shuffle=False, smooth=0)
    
    X_trans = targ_enc.fit_transform(df.loc[:, [col]], df[target_col])

    df_new = pd.concat([df.drop(col, axis=1), pd.DataFrame(X_trans, df.index, [f"{col}_encoded"])], axis=1)
    return df_new

In [17]:
df_targ_encoded = target_encoding(df_encoded, "brewery_name", "review_overall")
df_targ_encoded.head(10)

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,beer_abv,...,beer_style_Scottish Ale,beer_style_Scottish Gruit / Ancient Herbed Ale,beer_style_Smoked Beer,beer_style_Tripel,beer_style_Vienna Lager,beer_style_Weizenbock,beer_style_Wheatwine,beer_style_Winter Warmer,beer_style_Witbier,brewery_name_encoded
764128,144,884649601,4.5,4.0,4.0,BeerAdvocate,4.0,4.0,Special Amber,5.0,...,0,0,0,0,1,0,0,0,0,3.675758
1417077,139,885340801,4.0,3.5,3.0,BeerAdvocate,3.5,4.0,Tremont Ale,4.8,...,0,0,0,0,0,0,0,0,0,3.444149
78405,140,886723201,4.5,4.0,4.0,BeerAdvocate,4.0,4.5,Sierra Nevada Bigfoot Barleywine Style Ale,9.6,...,0,0,0,0,0,0,0,0,0,4.052314
1526516,45,887155201,4.0,2.5,3.0,Todd,3.5,3.5,Brooklyn Lager,5.2,...,0,0,0,0,0,0,0,0,0,3.906054
1526153,45,887414401,3.0,4.0,3.0,BeerAdvocate,3.0,3.0,Brooklyn East India Pale Ale,6.8,...,0,0,0,0,0,0,0,0,0,3.906054
1037995,100,887414401,4.0,3.5,3.5,Todd,3.5,4.0,McNeill's Firehouse Amber Ale,5.6,...,0,0,0,0,0,0,0,0,0,3.710673
1037602,100,887673601,4.0,3.5,4.0,Todd,3.0,3.5,McNeill's Champ Ale,5.5,...,0,0,0,0,0,0,0,0,0,3.710673
921890,155,887673601,4.5,3.0,3.0,BeerAdvocate,4.0,4.5,Lager,5.0,...,0,0,0,0,0,0,0,0,0,3.394291
769741,42,887760001,4.5,4.0,4.0,Todd,4.0,4.5,Ommegang (Abbey Ale),8.5,...,0,0,0,0,0,0,0,0,0,4.015282
1029677,138,888019201,4.0,4.0,4.0,BeerAdvocate,3.5,4.0,Spitfire (Premium Ale Export),4.5,...,0,0,0,0,0,0,0,0,0,3.486377

In [18]:
len(pd.unique(df_targ_encoded["brewery_name_encoded"]))

12139

I think that the target encoder is considering the target variable for each specific review when encoding the brewery name, should be fixed to the average rating of that brewery name

### scaling

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler(with_mean=False) # Sparse due to one-hot-encoding

#numerical_df = df_targ_encoded.drop(["brewery_id", "review_time", ], axis=1)

KeyError: "['brewery_id', 'review_time'] not found in axis"

user or item based collaborative filtering?

user based:  
here is the most similar user, here are the beers they liked

item based:  
here are some similar beers to ones you liked

In [ ]:
beers = len(pd.unique(df_targ_encoded["beer_name"]))
users = len(pd.unique(df_targ_encoded["review_profilename"]))
print(f"# of beers: {beers}\t# of users: {users}")

# of beers: 43900	# of users: 32727

In [ ]:
beers / users * 100

134.14000672227823

comparable, but 34% more beers than users

I will go with an item based collaborative filter for the beer recommender system.  
But first I will have to transform the data into a user/item matrix

## Item-based Recommender

In [21]:
df.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
764128,144,Sprecher Brewing Company,884649601,4.5,4.0,4.0,BeerAdvocate,Vienna Lager,4.0,4.0,Special Amber,5.0,97
1417077,139,Shipyard Brewing Co.,885340801,4.0,3.5,3.0,BeerAdvocate,English Pale Ale,3.5,4.0,Tremont Ale,4.8,51
78405,140,Sierra Nevada Brewing Co.,886723201,4.5,4.0,4.0,BeerAdvocate,American Barleywine,4.0,4.5,Sierra Nevada Bigfoot Barleywine Style Ale,9.6,2671
1526516,45,Brooklyn Brewery,887155201,4.0,2.5,3.0,Todd,American Amber / Red Lager,3.5,3.5,Brooklyn Lager,5.2,148
1526153,45,Brooklyn Brewery,887414401,3.0,4.0,3.0,BeerAdvocate,English India Pale Ale (IPA),3.0,3.0,Brooklyn East India Pale Ale,6.8,147
1037995,100,McNeill's Brewery,887414401,4.0,3.5,3.5,Todd,American Amber / Red Ale,3.5,4.0,McNeill's Firehouse Amber Ale,5.6,325
1037602,100,McNeill's Brewery,887673601,4.0,3.5,4.0,Todd,American Pale Ale (APA),3.0,3.5,McNeill's Champ Ale,5.5,324
921890,155,Upper Canada Brewing Company,887673601,4.5,3.0,3.0,BeerAdvocate,American Pale Lager,4.0,4.5,Lager,5.0,44
769741,42,Brewery Ommegang,887760001,4.5,4.0,4.0,Todd,Dubbel,4.0,4.5,Ommegang (Abbey Ale),8.5,142
1029677,138,Shepherd Neame Ltd,888019201,4.0,4.0,4.0,BeerAdvocate,English Pale Ale,3.5,4.0,Spitfire (Premium Ale Export),4.5,305

In [22]:
df.loc[921890]

brewery_id                                     155
brewery_name          Upper Canada Brewing Company
review_time                              887673601
review_overall                                 4.5
review_aroma                                   3.0
review_appearance                              3.0
review_profilename                    BeerAdvocate
beer_style                     American Pale Lager
review_palate                                  4.0
review_taste                                   4.5
beer_name                                    Lager
beer_abv                                       5.0
beer_beerid                                     44
Name: 921890, dtype: object

In [30]:
def beerid_map(df: pd.DataFrame) -> dict:
    temp = df[["beer_name", "brewery_name", "beer_beerid"]].drop_duplicates()
    beer_dict = {}
    for _, row in temp.iterrows():
        beer_dict[row["beer_beerid"]] = (row["beer_name"], row["brewery_name"])
    
    return beer_dict

In [31]:
temp = beerid_map(df)

In [33]:
import json
with open("beerid_dict.json", "w") as f:
    json.dump(temp, f)

In [ ]:
def user_item_matrixer():
    #hot_encoded = pd.get_dummies(df[col], dtype=np.int64, prefix=col)