In [85]:
import pandas as pd
import numpy as np

In [86]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.25.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

### preprocessing

In [87]:
df = pd.read_csv("beer_reviews.csv")

# REMOVE REMOVE REMOVE
df = df.iloc[:10000]

df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9467.000000,10000.00000
mean,7385.332900,1.236778e+09,3.686150,3.635300,3.713700,3.630500,3.663750,7.033620,31463.47390
std,7624.972445,7.022574e+07,0.782007,0.751033,0.663684,0.760544,0.796382,2.085691,20647.57174
min,14.000000,9.882029e+08,1.000000,1.000000,1.000000,1.000000,1.000000,0.100000,178.00000
25%,765.000000,1.196636e+09,3.500000,3.000000,3.500000,3.000000,3.500000,5.400000,10784.00000
50%,2430.000000,1.254068e+09,4.000000,4.000000,4.000000,4.000000,4.000000,6.700000,33644.00000
75%,14879.000000,1.292663e+09,4.000000,4.000000,4.000000,4.000000,4.000000,8.600000,47988.00000
max,26990.000000,1.326250e+09,5.000000,5.000000,5.000000,5.000000,5.000000,16.000000,77070.00000

In [88]:
df.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883
5,1075,Caldera Brewing Company,1325524659,3.0,3.5,3.5,oline73,Herbed / Spiced Beer,3.0,3.5,Caldera Ginger Beer,4.7,52159
6,1075,Caldera Brewing Company,1318991115,3.5,3.5,3.5,Reidrover,Herbed / Spiced Beer,4.0,4.0,Caldera Ginger Beer,4.7,52159
7,1075,Caldera Brewing Company,1306276018,3.0,2.5,3.5,alpinebryant,Herbed / Spiced Beer,2.0,3.5,Caldera Ginger Beer,4.7,52159
8,1075,Caldera Brewing Company,1290454503,4.0,3.0,3.5,LordAdmNelson,Herbed / Spiced Beer,3.5,4.0,Caldera Ginger Beer,4.7,52159
9,1075,Caldera Brewing Company,1285632924,4.5,3.5,5.0,augustgarage,Herbed / Spiced Beer,4.0,4.0,Caldera Ginger Beer,4.7,52159

In [89]:
df.dropna(inplace=True)
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,9466.000000,9.466000e+03,9466.000000,9466.000000,9466.000000,9466.000000,9466.000000,9466.000000,9466.000000
mean,7548.136488,1.238477e+09,3.691686,3.643989,3.718466,3.635749,3.672195,7.033465,31337.291359
std,7669.762020,6.919676e+07,0.783104,0.756151,0.668332,0.763715,0.798362,2.085747,20632.641332
min,14.000000,9.882029e+08,1.000000,1.000000,1.000000,1.000000,1.000000,0.100000,178.000000
25%,765.000000,1.199477e+09,3.500000,3.500000,3.500000,3.000000,3.500000,5.400000,10784.000000
50%,2446.000000,1.255659e+09,4.000000,4.000000,4.000000,4.000000,4.000000,6.700000,33644.000000
75%,14879.000000,1.293153e+09,4.000000,4.000000,4.000000,4.000000,4.000000,8.600000,47710.000000
max,26990.000000,1.326250e+09,5.000000,5.000000,5.000000,5.000000,5.000000,16.000000,77006.000000

In [90]:
df.drop_duplicates(df.columns.delete(2), keep="first", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9465 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brewery_id          9465 non-null   int64
 1   brewery_name        9465 non-null   object
 2   review_time         9465 non-null   int64
 3   review_overall      9465 non-null   float64
 4   review_aroma        9465 non-null   float64
 5   review_appearance   9465 non-null   float64
 6   review_profilename  9465 non-null   object
 7   beer_style          9465 non-null   object
 8   review_palate       9465 non-null   float64
 9   review_taste        9465 non-null   float64
 10  beer_name           9465 non-null   object
 11  beer_abv            9465 non-null   float64
 12  beer_beerid         9465 non-null   int64
dtypes: float64(6), int64(3), object(4)
memory usage: 1.0+ MB

Only keep the latest review of a specific beer by reviewer

In [91]:
df = df.sort_values(by=['review_time']).drop_duplicates(["beer_beerid", "review_profilename"], keep="last")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9411 entries, 40 to 440
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brewery_id          9411 non-null   int64
 1   brewery_name        9411 non-null   object
 2   review_time         9411 non-null   int64
 3   review_overall      9411 non-null   float64
 4   review_aroma        9411 non-null   float64
 5   review_appearance   9411 non-null   float64
 6   review_profilename  9411 non-null   object
 7   beer_style          9411 non-null   object
 8   review_palate       9411 non-null   float64
 9   review_taste        9411 non-null   float64
 10  beer_name           9411 non-null   object
 11  beer_abv            9411 non-null   float64
 12  beer_beerid         9411 non-null   int64
dtypes: float64(6), int64(3), object(4)
memory usage: 1.0+ MB

pruning outliers

In [92]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,9411.000000,9.411000e+03,9411.000000,9411.000000,9411.000000,9411.000000,9411.000000,9411.000000,9411.000000
mean,7567.183084,1.238762e+09,3.690203,3.643396,3.717618,3.634895,3.671023,7.037492,31398.850494
std,7669.453581,6.902382e+07,0.783873,0.756919,0.668942,0.764551,0.799474,2.087676,20620.359464
min,14.000000,9.882029e+08,1.000000,1.000000,1.000000,1.000000,1.000000,0.100000,178.000000
25%,765.000000,1.199959e+09,3.500000,3.500000,3.500000,3.000000,3.500000,5.400000,10784.000000
50%,2446.000000,1.255983e+09,4.000000,4.000000,4.000000,4.000000,4.000000,6.700000,33644.000000
75%,14879.000000,1.293310e+09,4.000000,4.000000,4.000000,4.000000,4.000000,8.600000,47712.000000
max,26990.000000,1.326250e+09,5.000000,5.000000,5.000000,5.000000,5.000000,16.000000,77006.000000

In [93]:
print(7.043460 + (3 * 2.323306))

14.013378

In [94]:
df = df.query("review_overall > 0 and review_appearance > 0 and beer_abv < 14.013378")

In [95]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,9394.000000,9.394000e+03,9394.000000,9394.000000,9394.000000,9394.000000,9394.000000,9394.000000,9394.000000
mean,7579.571535,1.238852e+09,3.691718,3.644081,3.719023,3.635991,3.672238,7.022870,31394.475623
std,7670.852561,6.903954e+07,0.783270,0.757006,0.668217,0.764269,0.799288,2.060998,20637.918351
min,14.000000,9.882029e+08,1.000000,1.000000,1.000000,1.000000,1.000000,0.100000,178.000000
25%,765.000000,1.200198e+09,3.500000,3.500000,3.500000,3.000000,3.500000,5.400000,10784.000000
50%,2446.000000,1.256088e+09,4.000000,4.000000,4.000000,4.000000,4.000000,6.700000,33644.000000
75%,14879.000000,1.293336e+09,4.000000,4.000000,4.000000,4.000000,4.000000,8.600000,47763.750000
max,26990.000000,1.326250e+09,5.000000,5.000000,5.000000,5.000000,5.000000,14.000000,77006.000000

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9394 entries, 40 to 440
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brewery_id          9394 non-null   int64
 1   brewery_name        9394 non-null   object
 2   review_time         9394 non-null   int64
 3   review_overall      9394 non-null   float64
 4   review_aroma        9394 non-null   float64
 5   review_appearance   9394 non-null   float64
 6   review_profilename  9394 non-null   object
 7   beer_style          9394 non-null   object
 8   review_palate       9394 non-null   float64
 9   review_taste        9394 non-null   float64
 10  beer_name           9394 non-null   object
 11  beer_abv            9394 non-null   float64
 12  beer_beerid         9394 non-null   int64
dtypes: float64(6), int64(3), object(4)
memory usage: 1.0+ MB

### one hot encoding

In [97]:
def style_encoding(df: pd.DataFrame, col: str) -> pd.DataFrame:
    hot_encoded = pd.get_dummies(df[col], dtype=np.int64, prefix=col)
    df_new = pd.concat([df.drop(col, axis=1), hot_encoded], axis=1)
    return df_new

In [98]:
df_encoded = style_encoding(df, "beer_style")
#df_encoded = style_encoding(df_encoded, "brewery_name")
df_encoded.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,...,beer_style_Scotch Ale / Wee Heavy,beer_style_Scottish Ale,beer_style_Scottish Gruit / Ancient Herbed Ale,beer_style_Smoked Beer,beer_style_Tripel,beer_style_Vienna Lager,beer_style_Weizenbock,beer_style_Wheatwine,beer_style_Winter Warmer,beer_style_Witbier
40,163,Amstel Brouwerij B. V.,988202869,3.0,3.0,3.0,Brent,2.0,2.0,Amstel Light,...,0,0,0,0,0,0,0,0,0,0
9563,395,Bluegrass Brewing Co. - East St. Matthew's,996506774,4.0,5.0,4.0,Brent,4.0,4.0,Altbier,...,0,0,0,0,0,0,0,0,0,0
9187,395,Bluegrass Brewing Co. - East St. Matthew's,996507295,4.0,4.0,5.0,Brent,4.0,4.0,Dark Star Porter,...,0,0,0,0,0,0,0,0,0,0
2130,577,Isle Of Skye Brewery,1000848115,5.0,5.0,5.0,dennis,5.0,5.0,Black Cuillin,...,0,1,0,0,0,0,0,0,0,0
30,163,Amstel Brouwerij B. V.,1002109880,3.0,2.0,2.0,xXTequila,2.0,3.0,Amstel Light,...,0,0,0,0,0,0,0,0,0,0
6750,60,Cooperstown Brewing Company,1003836659,5.0,4.0,5.0,John,4.0,5.0,Strike Out Stout,...,0,0,0,0,0,0,0,0,0,0
18,163,Amstel Brouwerij B. V.,1010861086,2.5,3.0,3.0,jdhilt,2.0,2.0,Amstel Light,...,0,0,0,0,0,0,0,0,0,0
10,163,Amstel Brouwerij B. V.,1010963392,3.0,2.0,3.0,fodeeoz,2.5,2.5,Amstel Light,...,0,0,0,0,0,0,0,0,0,0
1937,850,Moon River Brewing Company,1013377051,3.5,3.5,4.0,Jason,4.0,3.5,Swamp Fox IPA,...,0,0,0,0,0,0,0,0,0,0
1864,850,Moon River Brewing Company,1013712158,4.5,4.5,4.0,Jason,4.5,4.5,Hefe-Weizen,...,0,0,0,0,0,0,0,0,0,0

In [99]:
len(pd.unique(df_encoded["brewery_name"]))

89

In [100]:
len(pd.unique(df_encoded["brewery_id"]))

89

^ Why are these different?

dataframe becomes too large if I one hot encode breweries. I will try target encoding (w.r.t. overall_rating) instead

In [101]:
from sklearn.preprocessing import TargetEncoder
def target_encoding(df: pd.DataFrame, col: str, target_col: str, smooth: bool = True) -> pd.DataFrame:
    if smooth:
        targ_enc = TargetEncoder(shuffle=False)
    else:
        targ_enc = TargetEncoder(shuffle=False, smooth=0)

    X_trans = targ_enc.fit_transform(df.loc[:, [col]], df[target_col])

    df_new = pd.concat([df.drop(col, axis=1), pd.DataFrame(X_trans, df.index, [f"{col}_encoded"])], axis=1)
    return df_new

In [102]:
df_targ_encoded = target_encoding(df_encoded, "brewery_name", "review_overall")
df_targ_encoded.head(10)

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,beer_abv,...,beer_style_Scottish Ale,beer_style_Scottish Gruit / Ancient Herbed Ale,beer_style_Smoked Beer,beer_style_Tripel,beer_style_Vienna Lager,beer_style_Weizenbock,beer_style_Wheatwine,beer_style_Winter Warmer,beer_style_Witbier,brewery_name_encoded
40,163,988202869,3.0,3.0,3.0,Brent,2.0,2.0,Amstel Light,3.50,...,0,0,0,0,0,0,0,0,0,2.758769
9563,395,996506774,4.0,5.0,4.0,Brent,4.0,4.0,Altbier,4.19,...,0,0,0,0,0,0,0,0,0,3.593066
9187,395,996507295,4.0,4.0,5.0,Brent,4.0,4.0,Dark Star Porter,5.60,...,0,0,0,0,0,0,0,0,0,3.593066
2130,577,1000848115,5.0,5.0,5.0,dennis,5.0,5.0,Black Cuillin,4.50,...,1,0,0,0,0,0,0,0,0,3.550331
30,163,1002109880,3.0,2.0,2.0,xXTequila,2.0,3.0,Amstel Light,3.50,...,0,0,0,0,0,0,0,0,0,2.758769
6750,60,1003836659,5.0,4.0,5.0,John,4.0,5.0,Strike Out Stout,4.60,...,0,0,0,0,0,0,0,0,0,3.726747
18,163,1010861086,2.5,3.0,3.0,jdhilt,2.0,2.0,Amstel Light,3.50,...,0,0,0,0,0,0,0,0,0,2.758769
10,163,1010963392,3.0,2.0,3.0,fodeeoz,2.5,2.5,Amstel Light,3.50,...,0,0,0,0,0,0,0,0,0,2.758769
1937,850,1013377051,3.5,3.5,4.0,Jason,4.0,3.5,Swamp Fox IPA,5.80,...,0,0,0,0,0,0,0,0,0,3.755961
1864,850,1013712158,4.5,4.5,4.0,Jason,4.5,4.5,Hefe-Weizen,5.50,...,0,0,0,0,0,0,0,0,0,3.755961

In [103]:
len(pd.unique(df_targ_encoded["brewery_name_encoded"]))

217

I think that the target encoder is considering the target variable for each specific review when encoding the brewery name, should be fixed to the average rating of that brewery name

user or item based collaborative filtering?

user based:  
here is the most similar user, here are the beers they liked

item based:  
here are some similar beers to ones you liked

In [104]:
beers = len(pd.unique(df_targ_encoded["beer_name"]))
users = len(pd.unique(df_targ_encoded["review_profilename"]))
print(f"# of beers: {beers}\t# of users: {users}")

# of beers: 712	# of users: 3144

In [105]:
beers / users * 100

22.646310432569976

comparable, but 34% more beers than users

I will go with an item based collaborative filter for the beer recommender system.  
But first I will have to transform the data into a user/item matrix

## Item-based Recommender

In [106]:
df.head(10)

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
40,163,Amstel Brouwerij B. V.,988202869,3.0,3.0,3.0,Brent,Light Lager,2.0,2.0,Amstel Light,3.50,436
9563,395,Bluegrass Brewing Co. - East St. Matthew's,996506774,4.0,5.0,4.0,Brent,Altbier,4.0,4.0,Altbier,4.19,1121
9187,395,Bluegrass Brewing Co. - East St. Matthew's,996507295,4.0,4.0,5.0,Brent,English Porter,4.0,4.0,Dark Star Porter,5.60,1123
2130,577,Isle Of Skye Brewery,1000848115,5.0,5.0,5.0,dennis,Scottish Ale,5.0,5.0,Black Cuillin,4.50,1557
30,163,Amstel Brouwerij B. V.,1002109880,3.0,2.0,2.0,xXTequila,Light Lager,2.0,3.0,Amstel Light,3.50,436
6750,60,Cooperstown Brewing Company,1003836659,5.0,4.0,5.0,John,English Stout,4.0,5.0,Strike Out Stout,4.60,178
18,163,Amstel Brouwerij B. V.,1010861086,2.5,3.0,3.0,jdhilt,Light Lager,2.0,2.0,Amstel Light,3.50,436
10,163,Amstel Brouwerij B. V.,1010963392,3.0,2.0,3.0,fodeeoz,Light Lager,2.5,2.5,Amstel Light,3.50,436
1937,850,Moon River Brewing Company,1013377051,3.5,3.5,4.0,Jason,American IPA,4.0,3.5,Swamp Fox IPA,5.80,2725
1864,850,Moon River Brewing Company,1013712158,4.5,4.5,4.0,Jason,Hefeweizen,4.5,4.5,Hefe-Weizen,5.50,2776

In [107]:
df.loc[18]

brewery_id                               163
brewery_name          Amstel Brouwerij B. V.
review_time                       1010861086
review_overall                           2.5
review_aroma                             3.0
review_appearance                        3.0
review_profilename                    jdhilt
beer_style                       Light Lager
review_palate                            2.0
review_taste                             2.0
beer_name                       Amstel Light
beer_abv                                 3.5
beer_beerid                              436
Name: 18, dtype: object

In [108]:
def beerid_map(df: pd.DataFrame) -> dict:
    temp = df[["beer_name", "brewery_name", "beer_beerid"]].drop_duplicates()
    beer_dict = {}
    for _, row in temp.iterrows():
        beer_dict[row["beer_beerid"]] = (row["beer_name"], row["brewery_name"])

    return beer_dict

In [109]:
temp = beerid_map(df)

In [110]:
import json
with open("beerid_dict.json", "w") as f:
    json.dump(temp, f)

In [111]:
df_trunc = df[["review_profilename", "beer_beerid", "review_overall", "review_taste", "review_palate", "review_aroma", "review_appearance"]]

In [112]:
df_trunc.head(10)

,review_profilename,beer_beerid,review_overall,review_taste,review_palate,review_aroma,review_appearance
40,Brent,436,3.0,2.0,2.0,3.0,3.0
9563,Brent,1121,4.0,4.0,4.0,5.0,4.0
9187,Brent,1123,4.0,4.0,4.0,4.0,5.0
2130,dennis,1557,5.0,5.0,5.0,5.0,5.0
30,xXTequila,436,3.0,3.0,2.0,2.0,2.0
6750,John,178,5.0,5.0,4.0,4.0,5.0
18,jdhilt,436,2.5,2.0,2.0,3.0,3.0
10,fodeeoz,436,3.0,2.5,2.5,2.0,3.0
1937,Jason,2725,3.5,3.5,4.0,3.5,4.0
1864,Jason,2776,4.5,4.5,4.5,4.5,4.0

(5 review metrics)

In [113]:
num_beers = df_trunc.beer_beerid.nunique()
num_users = df_trunc.review_profilename.nunique()

In [114]:
print(num_beers)
print(num_users)

730
3144

In [115]:
from numpy.linalg import norm   # keep it simple to one review per user

def norm_score(df: pd.DataFrame):
    # inplace
    review_cols = ["review_overall", "review_taste", "review_palate", "review_aroma", "review_appearance"]
    for ind, row in df.iterrows():
        df.loc[ind, "norm_reviews"] = norm(row[review_cols].values)




# want output of form x rows of users, y columns of beers, z rating criteria
def user_item_matrixer(df: pd.DataFrame):
    # reviews are normalized by user rating average

    num_beers = df.beer_beerid.nunique()
    num_users = df.review_profilename.nunique()
    beers = df.beer_beerid.unique()
    users = df.review_profilename.unique()

    ui_matrix = pd.DataFrame(index=users, columns=beers)
    norm_score(df)

    avg_user_ratings = df.groupby("review_profilename")["norm_reviews"].mean()

    for ind, row in df.iterrows():
        score = norm(row[review_cols].values) - avg_user_ratings[row["review_profilename"]]

        ui_matrix.loc[row["review_profilename"], row["beer_beerid"]] = score

    avg_beer_rating = df.groupby("beer_beerid")["norm_reviews"].mean()

    return ui_matrix, avg_user_ratings, avg_beer_rating

In [116]:
review_cols = ["review_overall", "review_taste", "review_palate", "review_aroma", "review_appearance"]
norms = []
for _, row in df.iterrows():
    norms.append(norm(row[review_cols]))
print(np.mean(norms))

8.262403895573422

In [117]:
import pickle
from os import path

In [132]:
if path.exists("ui_matrix_2.pkl"):
    print("saved matrix found!")
    #ui_matrix = pd.read_hdf("ui_matrix.h5")
    ui_matrix = pickle.load(open("ui_matrix_2.pkl", "rb"))
else:
    print("creating ui matrix!")
    ui_matrix, avg_user_rating, avg_beer_rating = user_item_matrixer(df_trunc)
    print("saving matrix!")
    #ui_matrix.to_hdf("ui_matrix.h5", key="ui_matrix")
    pickle.dump(ui_matrix, open("ui_matrix_2.pkl", "wb"))

print(ui_matrix.shape)
ui_matrix.head(10)

creating ui matrix!

<ipython-input-115-7ed347a01a62>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[ind, "norm_reviews"] = norm(row[review_cols].values)

saving matrix!
(3144, 730)

,436,1121,1123,1557,178,2725,2776,2780,2784,3003,...,75988,75989,76088,76508,76668,76685,76766,76780,76963,77006
Brent,-2.413464,1.104437,1.104437,NaN,NaN,NaN,NaN,NaN,NaN,0.849236,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dennis,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xXTequila,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
John,NaN,NaN,NaN,NaN,0.468318,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
jdhilt,-1.79481,-1.707437,0.207428,1.705062,0.58854,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fodeeoz,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jason,-3.512656,NaN,NaN,NaN,NaN,-0.29554,1.261756,0.591678,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MississaugaMatt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.703061,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Viking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.570907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
proc,-1.222136,NaN,1.222136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
from numpy import dot

# cosine similarity = a dot b / (norm(a) * norm(b))
def cossim(a, b):   # nans were causing nan output
    a_num = np.array(a, dtype=np.float_)
    b_num = np.array(b, dtype=np.float_)

    a_num = np.nan_to_num(a_num, copy=False)
    b_num = np.nan_to_num(b_num, copy=False)

    temp = dot(a_num, b_num)
    if temp == 0:
        return 0
    else:
        return temp / (norm(a_num) * norm(b_num))

# TODO SIMILARITY MATRIX WITH COSINE SIMILARITY

In [134]:
from sklearn.model_selection import train_test_split

Train with 99.9% of users and test remaining .1%  
This isn't a model based predictor so I don't need substantial testing

In [121]:
X_train, X_test = train_test_split(ui_matrix, test_size=0.001, random_state=21)

In [122]:
X_train.shape

(3140, 730)

In [123]:
X_test.shape

(4, 730)

In [124]:
X_train.tail(10)

,436,1121,1123,1557,178,2725,2776,2780,2784,3003,...,75988,75989,76088,76508,76668,76685,76766,76780,76963,77006
jazzyjeff13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Finite,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
perryw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
schoolcb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
awalk1227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Morris729,6.538348,8.291562,8.062258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
beals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
thebeerdoctor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
abfraser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mkfitz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
X_train = X_train.dropna(axis=1, how='all')
X_train.shape

(3140, 730)

In [126]:
X_train.dropna(axis=0, how='all', inplace=True)
X_train.shape

(3140, 730)

In [127]:
nulls = [i for i in ui_matrix.columns if i not in X_train.columns]
nulls

[]

In [128]:
X_test = X_test.drop(nulls, axis=1)
X_test.shape

(4, 730)

In [129]:
X_test.dropna(axis=0, how='all', inplace=True)
X_test.shape

(4, 730)

I will come back and find a better solution to the empty column in training set issue, but for now I just will use a tiny testing set and drop any beers that aren't in training

In [130]:
def sim_matrix(df: pd.DataFrame) -> pd.DataFrame:
    item_matrix = pd.DataFrame(index=df.columns, columns=df.columns)
    for i in df.columns:
        for j in df.columns:
            if i == j:
                item_matrix.loc[i, j] = 1
            else:
                temp = cossim(df.loc[:, i], df.loc[:, j])
                item_matrix.loc[i, j] = temp
    return item_matrix

In [135]:
item_matrix = sim_matrix(X_train)

In [136]:
item_matrix

,436,1121,1123,1557,178,2725,2776,2780,2784,3003,...,75988,75989,76088,76508,76668,76685,76766,76780,76963,77006
436,1,0.103516,0.13078,0.060519,0.023179,0.035047,0.084422,0.044321,0.020149,0.104315,...,0,0,0,0,0,0,0,0.046907,0.020111,0
1121,0.103516,1,0.415502,0.014241,0.039747,0.103725,0,0.070621,0.034403,0.325077,...,0,0,0,0,0.106758,0,0,0,0,0
1123,0.13078,0.415502,1,0.042911,0.082873,0.086035,0,0.079518,0.024685,0.292895,...,0.061369,0.085953,0,0,0.078892,0,0,0,0,0
1557,0.060519,0.014241,0.042911,1,0.192564,0.082163,0,0.095543,0.075704,0.052677,...,0,0,0,0,0,0,0,0,0,0
178,0.023179,0.039747,0.082873,0.192564,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76685,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
76766,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
76780,0.046907,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
76963,0.020111,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
77006,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [137]:
item_matrix[436]

436             1
1121     0.103516
1123      0.13078
1557     0.060519
178      0.023179
           ...
76685           0
76766           0
76780    0.046907
76963    0.020111
77006           0
Name: 436, Length: 730, dtype: object

In [138]:
item_matrix[436][1:].max()

0.1536999371880853

In [139]:
import sys
sys.getsizeof(item_matrix) / 1048576

16.537445068359375

16 mb for a 730x730 matrix, full size is like 44,000 x 44,000?

In [140]:
(16 * (44000**2 / 730**2)) / 1024

56.76487145805967

56 GB???

If it really is this massive, maybe I can circumvent by only loading relevant rows into memory at a time

In [169]:
class Recommender:

    def __init__(self, item_matrix: pd.DataFrame, beerid_dict: dict, avg_beer_ratings):
        self.item_matrix = item_matrix
        self.beerid_dict = beerid_dict
        self.beer_avgs = avg_beer_ratings
        self.recommendations = pd.DataFrame(columns=item_matrix.columns)

    def recommend(self, reviews: dict, user=str):
        # for every item not reviewed, multiply rating of an item review by
        # the similarity to item not reviewed, divided by similarity
        # reviews = {beer id: list of ratings}

        avg = self.user_avg(reviews)

        calculated_ratings = []
        for i in self.item_matrix.columns:
            if i not in reviews.keys():     # don't recommend a beer they've already had
                calculated_ratings.append(self._rec_helper(reviews, i, avg))
            else:
                calculated_ratings.append(np.NaN)

        self.recommendations.loc[user] = calculated_ratings

        # sort recommendations by value, take top three, input corresponding column into beerid->name dict
        temp = self.recommendations.loc[user].sort_values(ascending=False)[:3].index
        print(f"Top 3 Beers to Try!\n1. {self.beerid_dict[temp[0]]}\n2. {self.beerid_dict[temp[1]]}\n3. {self.beerid_dict[temp[2]]}")
        #print(self.recommendations.loc[user].sort_values(ascending=False)[:30])

    def _rec_helper(self, reviews, beer, avg) -> np.float_:
        # TODO: calculate the rating/similarity score for beer

        numerator = 0
        denominator = 0
        for i, ratings in reviews.items():
            score = norm(ratings)
            if i not in self.item_matrix.columns:
                # TODO
                # live updating of item_matrix
                continue
            else:
                numerator += self.item_matrix.loc[beer, i] * (score - self.beer_avgs[i])
                denominator += self.item_matrix.loc[beer, i]

        return (numerator / denominator) + avg

    @staticmethod
    def user_avg(reviews):
        temp = []
        for i in reviews.values():
            temp.append(norm(i))
        return np.mean(temp)

In [170]:
rec = Recommender(item_matrix, temp, avg_beer_rating)

In [171]:
rec.recommendations

Empty DataFrame
Columns: [436, 1121, 1123, 1557, 178, 2725, 2776, 2780, 2784, 3003, 3274, 1414, 3386, 3365, 3825, 7047, 2726, 2724, 5181, 5972, 6150, 1122, 4374, 6824, 6825, 7360, 7425, 7693, 7694, 7849, 8102, 8274, 8284, 8422, 8514, 8590, 8717, 8769, 8770, 8869, 8950, 9117, 9118, 1599, 9238, 9239, 9240, 9241, 9242, 9422, 5547, 10649, 11324, 11325, 11456, 10786, 12155, 12386, 12421, 12655, 12835, 13009, 13289, 13548, 13583, 4373, 13282, 14242, 14243, 14413, 14454, 15130, 15131, 15139, 15140, 15474, 15660, 15797, 15894, 16122, 966, 1413, 1681, 16491, 17059, 7324, 17124, 17162, 13112, 10656, 14592, 17610, 4371, 17010, 14591, 18533, 18573, 18713, 5617, 19309, ...]
Index: []

[0 rows x 730 columns]

In [172]:
for i in temp.items():
    print(i)

(436, ('Amstel Light', 'Amstel Brouwerij B. V.'))
(1121, ('Altbier', "Bluegrass Brewing Co. - East St. Matthew's"))
(1123, ('Dark Star Porter', "Bluegrass Brewing Co. - East St. Matthew's"))
(1557, ('Black Cuillin', 'Isle Of Skye Brewery'))
(178, ('Strike Out Stout', 'Cooperstown Brewing Company'))
(2725, ('Swamp Fox IPA', 'Moon River Brewing Company'))
(2776, ('Hefe-Weizen', 'Moon River Brewing Company'))
(2780, ("The Captain's Porter", 'Moon River Brewing Company'))
(2784, ('Trafalgar Abbey Belgian Spice Ale', 'Trafalgar Ales & Meads'))
(3003, ("Bearded Pat's Barleywine", "Bluegrass Brewing Co. - East St. Matthew's"))
(3274, ('Caldera Pilsener Bier', 'Caldera Brewing Company'))
(1414, ('Amstel Lager', 'Amstel Brouwerij B. V.'))
(3386, ('Amstel Bright', 'Amstel Brouwerij B. V.'))
(3365, ('Hell For Certain', "Bluegrass Brewing Co. - East St. Matthew's"))
(3825, ('Harboe Bjørnebryg (Bear Beer)', 'Harboes Bryggeri A/S'))
(7047, ('Champion Reserve IPA', 'The Seven Barrel Brewery'))
(2726, ('Claire De Lune', 'Moon River Brewing Company'))
(2724, ('Inspiration Ale', 'Moon River Brewing Company'))
(5181, ('Club Premium Lager', 'Accra Brewery Limited'))
(5972, ('Luna De Miel: Raspberry Meade', "Bluegrass Brewing Co. - East St. Matthew's"))
(6150, ('Honest Injun Stout', 'Catawba Valley Brewing Company'))
(1122, ('American Pale Ale', "Bluegrass Brewing Co. - East St. Matthew's"))
(4374, ("Rajah's Royal IPA", 'Harmon Restaurant & Brewery'))
(6824, ('E.S.B.', 'Broad Ripple Brew Pub'))
(6825, ('I.P.A.', 'Broad Ripple Brew Pub'))
(7360, ('Crystal Bitter Ale', 'No-Li Brewhouse'))
(7425, ('Cocker Hoop', 'Jennings Brothers PLC'))
(7693, ('La Binchoise Blonde Tradition', 'Brasserie La Binchoise (Malterie des Remparts)'))
(7694, ('La Binchoise Brune Tradition', 'Brasserie La Binchoise (Malterie des Remparts)'))
(7849, ('Ichthysaur IPA', 'Great Basin Brewing Co.'))
(8102, ('Lech Premium', 'Kompania Piwowarska'))
(8274, ('Trafalgar Celebration Ale', 'Trafalgar Ales & Meads'))
(8284, ('Wee Alec Heavy', 'Broad Ripple Brew Pub'))
(8422, ('La Binchoise Spéciale Noël (Reserve Special - USA)', 'Brasserie La Binchoise (Malterie des Remparts)'))
(8514, ('Bay Street Brown Ale', 'Moon River Brewing Company'))
(8590, ("Paddy's Irish Red", 'Trafalgar Ales & Meads'))
(8717, ('Savannah Fest Beer', 'Moon River Brewing Company'))
(8769, ('Columbus India Pale Ale', 'Pacific Coast Brewing Company'))
(8770, ('Killer Whale Stout', 'Pacific Coast Brewing Company'))
(8869, ('Winter Warmer', 'Trafalgar Ales & Meads'))
(8950, ('Firewater IPA', 'Catawba Valley Brewing Company'))
(9117, ('Jennings Cumberland Ale', 'Jennings Brothers PLC'))
(9118, ('Jennings Sneck Lifter', 'Jennings Brothers PLC'))
(1599, ('Back Yard India Pale Ale', 'Cooperstown Brewing Company'))
(9238, ('Santa Rosa Red', 'Anacapa Brewing Company'))
(9239, ('Hurricane Hefeweizen', 'Anacapa Brewing Company'))
(9240, ('Pierpont India Pale Ale', 'Anacapa Brewing Company'))
(9241, ('Chocolate Raspberry Stout', 'Anacapa Brewing Company'))
(9242, ('Offshore Amber Ale', 'Anacapa Brewing Company'))
(9422, ('Dublins Irish Ale', 'Anacapa Brewing Company'))
(5547, ('Red Stallion', 'Crescent City Brewhouse'))
(10649, ('Wheat Beer', 'Broad Ripple Brew Pub'))
(11324, ('Risky Biscuit Barleywine', 'Great Basin Brewing Co.'))
(11325, ('Truckee River Red Organic Ale', 'Great Basin Brewing Co.'))
(11456, ('Red Cuillin', 'Isle Of Skye Brewery'))
(10786, ('Dry Hop Red', 'Caldera Brewing Company'))
(12155, ('Bogemia', 'Stakhanovitz'))
(12386, ('Caldera OBF 15', 'Caldera Brewing Company'))
(12421, ('Amber Ale', 'No-Li Brewhouse'))
(12655, ('Jennings Crag Rat', 'Jennings Brothers PLC'))
(12835, ('Deviator Doppelbock', 'Pacific Coast Brewing Company'))
(13009, ('Pale Ale', 'No-Li Brewhouse'))
(13289, ('Oktoberfest', 'Broad Ripple Brew Pub'))
(13548, ('Bernard Celebration Lager', 'Bernard Family Brewery'))
(13583, ('Bernard Sváte&#269;ní Le\x9eák', 'Bernard Family Brewery'))
(4373, ('Point Defiance IPA', 'Harmon Restaurant & Brewery'))
(13282, ("King Don's Original Pumpkin Ale", 'Catawba Valley Brewing Company'))
(14242, ('Portside Amber Premium Ale', 'Trafalgar Ales & Meads'))
(14243, ('Harbour Gold Premium Pilsner', 'Trafalgar Ales & Meads'))
(14413, ('Brown Bear Ale', 'Catawba Valley Brewing Company'))
(14454, ("Mephistopheles' Metamorphosis", "Bluegrass Brewing Co. - East St. Matthew's"))
(15130, ('Dark Mild', 'Jennings Brothers PLC'))
(15131, ('Red Breast', 'Jennings Brothers PLC'))
(15139, ('Cross Buttock Ale', 'Jennings Brothers PLC'))
(15140, ('Jennings Best Bitter', 'Jennings Brothers PLC'))
(15474, ('Broad Ripple Lawnmower Pale Ale', 'Broad Ripple Brew Pub'))
(15660, ('Wobbly Bob APA', 'Broad Ripple Brew Pub'))
(15797, ('Old Smokey (Black Silk Smoked Porter)', "Bluegrass Brewing Co. - East St. Matthew's"))
(15894, ('Code Blue', 'Pacific Coast Brewing Company'))
(16122, ('Sakara Gold', 'Al Ahram Beverages Company'))
(966, ('Pike Street XXXXX Stout', 'Pike Pub & Brewery'))
(1413, ('Amstel 1870', 'Amstel Brouwerij B. V.'))
(1681, ('ESB', "Bluegrass Brewing Co. - East St. Matthew's"))
(16491, ("T.J.'s Best Bitter", 'Broad Ripple Brew Pub'))
(17059, ('Rege', "Brasserie d'Algiers"))
(7324, ('Nut Brown Ale', "Bluegrass Brewing Co. - East St. Matthew's"))
(17124, ('Brulle', "Brasserie d'Algiers"))
(17162, ('Chocolate Dunkel', 'No-Li Brewhouse'))
(13112, ('IPA', 'No-Li Brewhouse'))
(10656, ('Gem', 'Bath Ales Ltd'))
(14592, ('King Coconut Porter', 'Catawba Valley Brewing Company'))
(17610, ('Gwiniz Du', 'Brasserie Britt de Bretagne'))
(4371, ("Brown's Point ESB", 'Harmon Restaurant & Brewery'))
(17010, ('Wee Beast (Cuillin Beast)', 'Isle Of Skye Brewery'))
(14591, ('King Karma Ale', 'Catawba Valley Brewing Company'))
(18533, ('Elora ESB', 'Trafalgar Ales & Meads'))
(18573, ('Bernard Semi-dark Lager (polotmavy Lezak)', 'Bernard Family Brewery'))
(18713, ('Wort Hog Dort', "Bluegrass Brewing Co. - East St. Matthew's"))
(5617, ('Black Cobra Stout', 'Third Base Sports Bar & Brewery'))
(19309, ('Bernard Svetly Lezak', 'Bernard Family Brewery'))
(1598, ('Old Slugger', 'Cooperstown Brewing Company'))
(16892, ('Flying Aces Ale', 'Third Base Sports Bar & Brewery'))
(19459, ('Ar-Men Dorée', 'Brasserie Britt de Bretagne'))
(13152, ('La Binchoise Bière Des Ours (Berenbier)', 'Brasserie La Binchoise (Malterie des Remparts)'))
(19674, ('Ar-Men Ambrée', 'Brasserie Britt de Bretagne'))
(19895, ('White Rapids Ale', 'Third Base Sports Bar & Brewery'))
(16893, ('Golden Hawk Wheat', 'Third Base Sports Bar & Brewery'))
(19898, ('Helles Honey Bock', 'Third Base Sports Bar & Brewery'))
(16894, ('Red Rocket Amber Ale', 'Third Base Sports Bar & Brewery'))
(20017, ('Dark De Triomphe', 'Frog at Bercy Village, The'))
(20021, ('La Binchoise Rose Des Remparts', 'Brasserie La Binchoise (Malterie des Remparts)'))
(13153, ('La Binchoise Flora  Bière De Printemps', 'Brasserie La Binchoise (Malterie des Remparts)'))
(20038, ('Ar-Men Brune', 'Brasserie Britt de Bretagne'))
(20112, ('Dopple Weizen', 'San Francisco Brewing Company'))
(20199, ('Irish Amber Light', 'Trafalgar Ales & Meads'))
(20202, ('Trafalgar Celtic Ale', 'Trafalgar Ales & Meads'))
(20367, ('Oktoberfest', 'Third Base Sports Bar & Brewery'))
(20417, ('Homewrecker', "Bluegrass Brewing Co. - East St. Matthew's"))
(20504, ('Weizen', 'Bakushukan Clair (Kure Beer)'))
(20505, ('Alt', 'Bakushukan Clair (Kure Beer)'))
(20584, ('Oktoberfest', 'Great Basin Brewing Co.'))
(19558, ('Wild Wacky Wit', 'Moon River Brewing Company'))
(20757, ('Black River Imperial Stout', 'Moon River Brewing Company'))
(20758, ('Ogeechee Amber Ale', 'Moon River Brewing Company'))
(10793, ('Cauldron Brew', 'Caldera Brewing Company'))
(10788, ('Pilot Rock Porter', 'Caldera Brewing Company'))
(20901, ('80 Weight Mild Amber Scotch Ale', 'The Seven Barrel Brewery'))
(20986, ('Christian Firtal', 'Harboes Bryggeri A/S'))
(1415, ('Amstel Gold', 'Amstel Brouwerij B. V.'))
(10789, ('Caldera Oatmeal Stout', 'Caldera Brewing Company'))
(1418, ('Amstel Bock', 'Amstel Brouwerij B. V.'))
(21521, ('Bernard Cerne', 'Bernard Family Brewery'))
(10785, ('Ashland Amber', 'Caldera Brewing Company'))
(21607, ('Trafalgar Downrigger Double Bock', 'Trafalgar Ales & Meads'))
(16417, ('New Dublin Brown Ale', 'The Seven Barrel Brewery'))
(10784, ('Caldera IPA', 'Caldera Brewing Company'))
(22169, ('Richmodis Koelsch', 'Richmodis-Bräu'))
(22464, ('Goldhorn Club', 'Pivovarna Laško'))
(1589, ("Professor Gesser's Mind Numbing Ale", "Bluegrass Brewing Co. - East St. Matthew's"))
(22622, ('Halliburton On Trent', "Bluegrass Brewing Co. - East St. Matthew's"))
(16896, ('Tilted Kilt', 'Third Base Sports Bar & Brewery'))
(22213, ('Brown Nose Ale', 'Third Base Sports Bar & Brewery'))
(22746, ('Zhigulovskoye', 'Voronezhsky Brewery'))
(22808, ('Harboe Den Glada Danskens Lättöl', 'Harboes Bryggeri A/S'))
(23013, ('Brouemont India Pale', 'Micro-Brasserie Brouemont'))
(23014, ('Brouemont Imperial India Pale Ale', 'Micro-Brasserie Brouemont'))
(23015, ('Brouemont Russian Imperial Stout', 'Micro-Brasserie Brouemont'))
(23118, ('La Cisterciènne Bruna', 'Brasserie La Binchoise (Malterie des Remparts)'))
(23282, ('Golden Host', 'Jennings Brothers PLC'))
(23290, ('Dry Hop Orange', 'Caldera Brewing Company'))
(23315, ('Netto "24" Fødselsdags-Bryg', 'Harboes Bryggeri A/S'))
(22615, ('Harboe Classic 110', 'Harboes Bryggeri A/S'))
(23326, ('Amber IPA', 'Clockwork Beer Co, The'))
(23327, ('Gosch', 'Clockwork Beer Co, The'))
(23328, ('Red Alt Ale', 'Clockwork Beer Co, The'))
(23329, ('Original Lager', 'Clockwork Beer Co, The'))
(23616, ('Scotch Ale', "Bluegrass Brewing Co. - East St. Matthew's"))
(23668, ('Weizen', 'Micro-Brasserie Brouemont'))
(23904, ('Britt Rousse', 'Brasserie Britt de Bretagne'))
(24016, ('Mai-Rye-Bock', 'Moon River Brewing Company'))
(24057, ('Galleria Espresso Stout', 'Moon River Brewing Company'))
(24185, ('Vintage 03 Scottish Wee Heavy', "Bluegrass Brewing Co. - East St. Matthew's"))
(45450, ('Smoke Creek Rauchbock', 'Great Basin Brewing Co.'))
(24443, ('Katies Cream Ale', 'Great Basin Brewing Co.'))
(24444, ('Black Rock ESB', 'Great Basin Brewing Co.'))
(22817, ('Harboe Pilsner', 'Harboes Bryggeri A/S'))
(22604, ('Harboe Bjørnebryg Extra Stark (Bear Beer Extra Strong)', 'Harboes Bryggeri A/S'))
(4372, ('Puget Sound Porter', 'Harmon Restaurant & Brewery'))
(25049, ('Portside Amber', 'Trafalgar Ales & Meads'))
(25101, ("Farmer Ted's Cream Ale", 'Catawba Valley Brewing Company'))
(25181, ('Gribousine Malonne Brune', 'Brasserie La Binchoise (Malterie des Remparts)'))
(25214, ('Gribousine Malonne Blond', 'Brasserie La Binchoise (Malterie des Remparts)'))
(25250, ('Victory Pale Ale', "Emmett's Brewing Company"))
(25251, ('1 A.M. Ale', "Emmett's Brewing Company"))
(25252, ('Imperial IPA', "Emmett's Brewing Company"))
(25414, ('Caldera Pale Ale', 'Caldera Brewing Company'))
(25520, ('Cerveza ChileBeso', 'Great Basin Brewing Co.'))
(26007, ("Gribousine D'Hiver", 'Brasserie La Binchoise (Malterie des Remparts)'))
(26418, ('Wheat Ale', 'Destiny Brewing Company'))
(26419, ('Red Rye Ale', 'Destiny Brewing Company'))
(26420, ('Pale Ale', 'Destiny Brewing Company'))
(26562, ('Moon Dance Pale Ale', 'Moon River Brewing Company'))
(26651, ('12 Year Anniversary Ale', 'No-Li Brewhouse'))
(26686, ('Granary Wheat Premium Ale', 'Trafalgar Ales & Meads'))
(11709, ('Hebridean Gold Porridge Oat Ale', 'Isle Of Skye Brewery'))
(26817, ('Pumpkin Ale', 'Destiny Brewing Company'))
(26853, ('Kolsch', "Emmett's Brewing Company"))
(26854, ('Centennial Amber Ale', "Emmett's Brewing Company"))
(26856, ('Oatmeal Stout', "Emmett's Brewing Company"))
(26909, ('Devanha Scottish XXX Ale', 'Isle Of Skye Brewery'))
(27229, ('Wheezy Heifer', 'Moon River Brewing Company'))
(27347, ('Bourbon Barrel Smoked Porter', "Bluegrass Brewing Co. - East St. Matthew's"))
(22616, ('Harboe Guldøl (Harboe Beer Gold)', 'Harboes Bryggeri A/S'))
(21652, ('Meister', 'Al Ahram Beverages Company'))
(27585, ('Stella Premium', 'Al Ahram Beverages Company'))
(27586, ('Stella', 'Al Ahram Beverages Company'))
(27588, ('Stella Export', 'Al Ahram Beverages Company'))
(27589, ('Meister Max', 'Al Ahram Beverages Company'))
(27590, ('Sakara Red', 'Al Ahram Beverages Company'))
(27596, ('Elora Grand Lager', 'Trafalgar Ales & Meads'))
(27597, ('Elora Irish Ale', 'Trafalgar Ales & Meads'))
(27664, ('Newark IPA', 'Destiny Brewing Company'))
(27666, ('Holiday Ale', 'Destiny Brewing Company'))
(27753, ('Kolsch', "Bluegrass Brewing Co. - East St. Matthew's"))
(22608, ('Harboe Julebryg', 'Harboes Bryggeri A/S'))
(27799, ('Sweet Stout', 'Destiny Brewing Company'))
(27828, ('Oak Aged Stout', 'Catawba Valley Brewing Company'))
(27982, ('Winter Ale', 'No-Li Brewhouse'))
(28096, ('Ar-Men Blonde', 'Brasserie Britt de Bretagne'))
(28100, ('Zahre Affumicata', 'Sauris AgriBeer S.a.s'))
(14589, ('Indian Red Head', 'Catawba Valley Brewing Company'))
(4370, ('Pinnacle Peak Pale Ale', 'Harmon Restaurant & Brewery'))
(20022, ('La Binchoise La Belge Biere Speciale', 'Brasserie La Binchoise (Malterie des Remparts)'))
(28469, ('Zahre Chiara Pilsen', 'Sauris AgriBeer S.a.s'))
(29142, ('Oatboy Imperial IPA', 'Moon River Brewing Company'))
(29198, ('Ar-Men Blanche', 'Brasserie Britt de Bretagne'))
(29204, ('Horse Piss Beer', "Bluegrass Brewing Co. - East St. Matthew's"))
(29227, ('Batch 1300', "Bluegrass Brewing Co. - East St. Matthew's"))
(29687, ("Jefferson's Reserve Bourbon Barrel Stout", "Bluegrass Brewing Co. - East St. Matthew's"))
(29727, ('Trafalgar Bock', 'Trafalgar Ales & Meads'))
(30034, ('Forester Pale Ale', 'The Two Metre Tall Company Pty Ltd'))
(30199, ('Zahre Canapa', 'Sauris AgriBeer S.a.s'))
(30571, ('Tom Fool', 'Jennings Brothers PLC'))
(30682, ('Trafalgar Critical Mass', 'Trafalgar Ales & Meads'))
(30780, ('Old Skool', 'Eastwood The Brewer (John Eastwood)'))
(30983, ('OX', 'Bernard Family Brewery'))
(959, ('Pike Pale Ale', 'Pike Pub & Brewery'))
(31507, ('Foghorn Porter', 'Anacapa Brewing Company'))
(31508, ('English Summer Ale', 'Anacapa Brewing Company'))
(31630, ('Trafalgar Red Hill Mild', 'Trafalgar Ales & Meads'))
(31973, ('Mt. Takhoma Blonde Ale', 'Harmon Restaurant & Brewery'))
(32084, ('Black Night Black Lager', 'Third Base Sports Bar & Brewery'))
(32141, ('X-Extra Pale Ale', 'Moon River Brewing Company'))
(32264, ('Braveheart Beir', 'Harmon Restaurant & Brewery'))
(32265, ('Red Wolf Cherry Wheat', 'Harmon Restaurant & Brewery'))
(32306, ('Farmhouse Ale', 'Broad Ripple Brew Pub'))
(32368, ('Harboe Red Beer', 'Harboes Bryggeri A/S'))
(32371, ('Whiskey River IPA', 'Catawba Valley Brewing Company'))
(32374, ('Puget Sound Vanilla Porter', 'Harmon Restaurant & Brewery'))
(32621, ('La Britt Blonde', 'Brasserie Britt de Bretagne'))
(32661, ('White Oak Weissbier', 'Trafalgar Ales & Meads'))
(32676, ('One Hop Wonder IPA', 'Harmon Restaurant & Brewery'))
(22609, ('Harboe Årgangssbryg', 'Harboes Bryggeri A/S'))
(32179, ('Christian Firtal Guldøl', 'Harboes Bryggeri A/S'))
(32710, ('Strawberry Anti-Social', 'Trafalgar Ales & Meads'))
(32711, ('Debau Cherry Bitter Ale', 'Trafalgar Ales & Meads'))
(31935, ('Pilsner', 'Broad Ripple Brew Pub'))
(32759, ('Brockway Brown', 'Anacapa Brewing Company'))
(33242, ('Harmon Killer Brew, Version 9', 'Harmon Restaurant & Brewery'))
(33272, ('Pumpkin Ale', 'Broad Ripple Brew Pub'))
(33448, ("Ivan's Ale", 'Trafalgar Ales & Meads'))
(33584, ('Amstel (Pure Filtered)', 'Amstel Brouwerij B. V.'))
(33624, ("Hoppin' To Heaven IPA", "Hoppin' Frog Brewery"))
(33644, ('B.O.R.I.S. The Crusher Oatmeal-Imperial Stout', "Hoppin' Frog Brewery"))
(33662, ('Bodacious Black & Tan', "Hoppin' Frog Brewery"))
(33706, ('Mild Thing', 'Harmon Restaurant & Brewery'))
(33772, ('13th Anniversary Imperial India Pale Ale', 'No-Li Brewhouse'))
(33927, ('Gulden Fraug Belgian Style Ale', "Hoppin' Frog Brewery"))
(34569, ('The Tater Ale', 'Moon River Brewing Company'))
(34636, ('Etrange De Leah', "Bluegrass Brewing Co. - East St. Matthew's"))
(34637, ('Darby Blonde Ale', "Bluegrass Brewing Co. - East St. Matthew's"))
(34739, ('Harboe Vib Pilsner Classic Landlord', 'Harboes Bryggeri A/S'))
(35064, ('Meta Export Lager', 'Meta Abo Brewery - Ethiopia'))
(34738, ('Harboe Vib Pilsner Håndbajer', 'Harboes Bryggeri A/S'))
(35228, ("Ankle Biter Ale '07", 'Broad Ripple Brew Pub'))
(35351, ('Espresso Stout', 'Anacapa Brewing Company'))
(35378, ('Heine Brothers Coffee Stout', "Bluegrass Brewing Co. - East St. Matthew's"))
(960, ('Pike India Pale Ale', 'Pike Pub & Brewery'))
(35386, ('Festival Bock', 'Crescent City Brewhouse'))
(35880, ('SantiAmber Ale', 'Calapooia Brewing Company'))
(35881, ('Riverdog ESB', 'Calapooia Brewing Company'))
(35882, ("Devil's Hole Stout", 'Calapooia Brewing Company'))
(35982, ('Sakara King', 'Al Ahram Beverages Company'))
(36035, ("Somethin' Lite", 'Calapooia Brewing Company'))
(36036, ('Big Aft Pale Ale', 'Calapooia Brewing Company'))
(36037, ("'Pooya Porter", 'Calapooia Brewing Company'))
(36038, ('Flood Stage Red', 'Calapooia Brewing Company'))
(36039, ('Calapooia Barleywine', 'Calapooia Brewing Company'))
(36167, ('RIP - Russian Imperial Porter', "Bluegrass Brewing Co. - East St. Matthew's"))
(5182, ("REDD'S", 'Kompania Piwowarska'))
(49490, ('Solar Winds', 'No-Li Brewhouse'))
(36367, ('Cleansing Ale', 'The Two Metre Tall Company Pty Ltd'))
(36380, ('Trafalgar Maple Bock', 'Trafalgar Ales & Meads'))
(36470, ('Harboe Silver Beer 3,5%', 'Harboes Bryggeri A/S'))
(36484, ('Harbroe Classic Beer 2,8%', 'Harboes Bryggeri A/S'))
(36580, ('Harboe Pilsner 2,8%', 'Harboes Bryggeri A/S'))
(36609, ('Harboe Påskebryg 2,8%', 'Harboes Bryggeri A/S'))
(36661, ('Tigh Dearg Ale', 'Isle Of Skye Brewery'))
(36720, ('Harboe Pilsner 3,5%', 'Harboes Bryggeri A/S'))
(36862, ('Wild Frog Wheat Ale', "Hoppin' Frog Brewery"))
(37175, ('Harboe Dunkel', 'Harboes Bryggeri A/S'))
(37237, ('Harboe Premium Traditional Pilsner 4.6%', 'Harboes Bryggeri A/S'))
(37518, ('Mean Manalishi Double I.P.A.', "Hoppin' Frog Brewery"))
(37559, ('J.T. Memorial Kolsch', 'Harmon Restaurant & Brewery'))
(37917, ('Exotic Erotic Passion Fruit Ale', 'Caldera Brewing Company'))
(37930, ('Neder Keller Bier', 'Brauerei Neder'))
(37952, ('Blackwater Uber Pale Ale', 'Catawba Valley Brewing Company'))
(38082, ('El Dorado Premium Pilsener', 'Al Ahram Beverages Company'))
(38196, ('Weizenbock', "Bluegrass Brewing Co. - East St. Matthew's"))
(38200, ('Drunkelweizen', "Bluegrass Brewing Co. - East St. Matthew's"))
(38212, ('Yankee Clipper IPA', 'Calapooia Brewing Company'))
(38226, ('Dixie Crystal Beer', 'Moon River Brewing Company'))
(38233, ('Harboe Sommarbrygg', 'Harboes Bryggeri A/S'))
(38414, ('Extra Pale Ale', 'Broad Ripple Brew Pub'))
(38540, ('Harboe Kräftöl', 'Harboes Bryggeri A/S'))
(38552, ('Trafalgar Smoked Oatmeal Stout', 'Trafalgar Ales & Meads'))
(38865, ('Trafalgar Peppermint Porter', 'Trafalgar Ales & Meads'))
(38866, ('Trafalgar Black Bullet', 'Trafalgar Ales & Meads'))
(38982, ('Smashing Berry Ale', "Hoppin' Frog Brewery"))
(39007, ("Herr Kevin's Alt Bier", 'Broad Ripple Brew Pub'))
(39008, ('Monon Porter', 'Broad Ripple Brew Pub'))
(39009, ('Dual Citizenship Ale', 'Broad Ripple Brew Pub'))
(39215, ('Oktoberfest', "Bluegrass Brewing Co. - East St. Matthew's"))
(39289, ('American Pale Ale', 'Bluegrass Brewing Co.'))
(39314, ('Telford Porter', 'Conwy Brewery Ltd'))
(39360, ('Anvil Steam', "Bluegrass Brewing Co. - East St. Matthew's"))
(39606, ('Leviathan Imperial Stout', 'Pacific Coast Brewing Company'))
(39886, ('10 Year Clelebration Ale', 'Harmon Restaurant & Brewery'))
(40028, ('Sheltowee Hop-A-Lot IPA', "Bluegrass Brewing Co. - East St. Matthew's"))
(40140, ("Farmer Ted's Farmhouse Ale", 'Catawba Valley Brewing Company'))
(40153, ('Silk Porter', "Hoppin' Frog Brewery"))
(40248, ('Fresh Hop Rye', 'Calapooia Brewing Company'))
(40319, ('Freiherrn Pils', 'Brauerei Aldersbach'))
(40336, ('Sheltowee Sunrise Golden Ale', "Bluegrass Brewing Co. - East St. Matthew's"))
(40448, ('BourbonDog ESB', 'Calapooia Brewing Company'))

In [173]:
# lets say I really like the costco beers and I don't like a random stout
test_ratings = {65209: [2, 2, 1, 3, 3], 66603: [4, 5, 4, 3, 4], 66619: [5, 5, 5, 5, 5]}

In [174]:
rec.recommend(test_ratings, "test")

Top 3 Beers to Try!
1. ('Gulden Fraug Belgian Style Ale', "Hoppin' Frog Brewery")
2. ("Mephistopheles' Metamorphosis", "Bluegrass Brewing Co. - East St. Matthew's")
3. ('Victory Pale Ale', "Emmett's Brewing Company")

<ipython-input-169-e496cbe44096>:45: RuntimeWarning: invalid value encountered in scalar divide
  return (numerator / denominator) + avg

In [168]:
rec.recommendations

,436,1121,1123,1557,178,2725,2776,2780,2784,3003,...,75988,75989,76088,76508,76668,76685,76766,76780,76963,77006
test,11.465083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.458193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN